### ISSUE TITLE
could not install conductor with postgress persistance option using docker-compose  

### ISSUE THREAD

**Issue by johnico** [Netflix/conductor-community#91]
I am trying to follow the simple tutorial of netflix conductor but could not run the postgress or any other persistence option 

i have got APPLICATION FAILED TO START and can not use the persistance option 

conductor 3.9.10  using docker compose 
os: mac /windows 

`docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up`

```
conductor-server_1  | 5772 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.10.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.10.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.conductor.dao.MetadataDAO' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
conductor-server_1  | 5782 [main] INFO  org.apache.catalina.core.StandardService [] - Stopping service [Tomcat]
conductor-server_1  | 5815 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener [] -
conductor-server_1  |
conductor-server_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
conductor-server_1  | 5853 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter [] -
conductor-server_1  |
conductor-server_1  | ***************************
conductor-server_1  | APPLICATION FAILED TO START
conductor-server_1  | ***************************
conductor-server_1  |
conductor-server_1  | Description:
conductor-server_1  |
conductor-server_1  | Parameter 2 of constructor in com.netflix.conductor.core.execution.DeciderService required a bean of type 'com.netflix.conductor.dao.MetadataDAO' that could not be found.
conductor-server_1  |
conductor-server_1  |
conductor-server_1  | Action:
conductor-server_1  |
conductor-server_1  | Consider defining a bean of type 'com.netflix.conductor.dao.MetadataDAO' in your configuration.
conductor-server_1  |
```

**Comment by milhouse228** [comment]
I'm stuck in get started guide because this problem.

**Comment by milhouse228** [comment]
=/

**Comment by BirknerAlex** [comment]
Same issue with using MySQL

**Comment by biswarup1290dass** [comment]
I followed @johnico 's comment and  with inputs from the following links :
- https://stackoverflow.com/questions/72878515/could-run-netflix-conductor-with-postgress
- https://github.com/Netflix/conductor/issues/3016#issuecomment-1159159236
added the below line to my `server/build.gradle` file 
> `runtimeOnly "com.netflix.conductor:conductor-postgres-persistence:3.11.3`

Initially I got some error while running the `docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up` command as shown below:

```
#0 328.8 	at org.gradle.api.internal.tasks.PropertyFileCollection.visitChildren(PropertyFileCollection.java:48)
#0 328.8 	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
#0 328.8 	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:375)
#0 328.8 	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:51)
#0 328.8 	at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputFileProperty(DefaultInputFingerprinter.java:131)
#0 328.8 	... 78 more
#0 328.8 Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.netflix.conductor:conductor-postgres-persistence:3.9.10.
#0 328.8 Required by:
#0 328.8     project :conductor-server
#0 328.8
#0 328.8
#0 328.8 * Get more help at https://help.gradle.org
#0 328.8
#0 328.8 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
#0 328.8
#0 328.8 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
#0 328.8
#0 328.8 See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
#0 328.8
#0 328.8 Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
#0 328.8
#0 328.8 BUILD FAILED in 5m 28sPlease consult deprecation warnings for more details.
#0 328.8
#0 328.8 151 actionable tasks: 151 executed
#0 328.8
#0 328.8 Publishing build scan...
#0 330.1 https://gradle.com/s/ccesx7qnz5cha
#0 330.1
------
failed to solve: executor failed running [/bin/sh -c ./gradlew build -x test --stacktrace]: exit code: 1
```

When I found out that I was using some deprecated version (`3.9.10`) of the `conductor-postgres-persistence` maven dependency in the `build.gradle` file

I fetched an available version from here https://mvnrepository.com/artifact/com.netflix.conductor/conductor-postgres-persistence (`3.11.3`).

The `docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up` command worked fine after that.

**Comment by yuri1969** [comment]
@Dorjpalam This is Gradle's Groovy DSL syntax. Put that new line, for example, just under the existing `runtimeOnly "org.glassfish.jaxb:jaxb-runtime:${revJAXB}"` line.

**Comment by manan164** [comment]
Hi @Dorjpalam , The fix suggested by @yuri1969  should work. If not,  we can [chat](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) here

**Comment by samjain215** [comment]
Hi @manan164  The fix does not work on the latest checkout. 

`ocker-conductor-server-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1  | 37261 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemTaskRegistry' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/tasks/SystemTaskRegistry.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SUB_WORKFLOW' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/tasks/SubWorkflow.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'startWorkflowOperation' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/operation/StartWorkflowOperation.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout]
docker-conductor-server-1  | {"cluster_name":"docker-cluster","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":25,"active_shards":25,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":25,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar!/:5.3.22]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar!/:5.3.22]
`

**Comment by manan164** [comment]
Hi @MacyFonseca , can you please paste the error here?

**Comment by MacyFonseca** [comment]
@manan164 this is one of the errors that appears in the docker logs:
`
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-05-04 17:13:51 59237 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
2023-05-04 17:13:51 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'queueAdminResource' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/QueueAdminResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultEventQueueProcessor' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/events/queue/DefaultEventQueueProcessor.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'systemTaskRegistry' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/tasks/SystemTaskRegistry.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'SET_VARIABLE' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/tasks/SetVariable.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/core/dal/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexRestDAO': Invocation of init method failed; nested exception is org.elasticsearch.client.ResponseException: method [GET], host [http://es:9200], URI [/_cluster/health?timeout=30s&wait_for_status=green], status line [HTTP/1.1 408 Request Timeout]
`

**Comment by missioncoding** [comment]
I am facing the issue even after adding the dependency line

conductor-ui       | Starting the development server...
conductor-ui       | 
conductor-server   | 4522 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext [] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'metadataResource' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/MetadataResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'metadataServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.14.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.14.0-SNAPSHOT.jar!/com/netflix/conductor/service/MetadataServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.conductor.dao.MetadataDAO' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
conductor-server   | 4536 [main] INFO  org.apache.catalina.core.StandardService [] - Stopping service [Tomcat]
conductor-server   | 4567 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener [] - 
conductor-server   | 
conductor-server   | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
conductor-server   | 4603 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter [] - 
conductor-server   | 
conductor-server   | ***************************
conductor-server   | APPLICATION FAILED TO START
conductor-server   | ***************************
conductor-server   | 
conductor-server   | Description:
conductor-server   | 
conductor-server   | Parameter 0 of constructor in com.netflix.conductor.service.MetadataServiceImpl required a bean of type 'com.netflix.conductor.dao.MetadataDAO' that could not be found.
conductor-server   | 
conductor-server   | 
conductor-server   | Action:
conductor-server   | 
conductor-server   | Consider defining a bean of type 'com.netflix.conductor.dao.MetadataDAO' in your configuration.
